spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventorize
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect